Add CUDA 11.8
conda-forge/nvcc-feedstock pull request #94
Opened 2022-10-05 17:47 UTC by bdice

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Adds CUDA 11.8. Depends on https://github.com/conda-forge/docker-images/pull/217, https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/207. cc: @m3vaz

Following the example of #77, #83. Instructions here: https://conda-forge.org/docs/maintainer/knowledge_base.html#adding-support-for-a-new-cuda-version

2022-10-05 17:47 UTC, conda-forge-linter commented
Hi! This is the friendly automated conda-forge-linting service.

I just wanted to let you know that I linted all conda-recipes in your PR (```recipe```) and found it was in an excellent condition.

2022-10-05 17:47 UTC, bdice commented
@conda-forge-admin, please rerender

2022-10-06 10:04 UTC, jaimergp requested changes
Please do not merge yet. Thanks!

2022-11-30 09:01 UTC, jakirkham commented
@conda-forge-admin, please re-render

2022-12-01 19:48 UTC, jakirkham approved these changes

2022-12-01 20:19 UTC, bdice commented
@conda-forge-admin, please re-render

2022-12-01 20:35 UTC, bdice commented
@conda-forge-admin, please re-render

2022-12-01 20:47 UTC, jakirkham commented on recipe/conda_build_config.yaml
> -  - 10.0   # [linux64 or win]
Windows CUDA 10.0 is dropped here as it is incompatible with `vs2019`. Given there are already packages for it and conda-forge has largely dropped CUDA 10.0, we are skipping Windows CUDA 10.0 here

2022-12-01 21:26 UTC, jakirkham commented
The Windows CUDA 11.8 build had failed due to a checksum issue. Summarized the problem here ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/216#discussion_r1037513019 ) and submitted a fix ( https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/218 ) that has since been merged. Restarting CI to clear that issue out

2022-12-01 22:01 UTC, merged

2022-12-01 22:01 UTC, jakirkham commented
Thanks Bradley! 🙏